language: node_js
node_js:
  - "7"
before_install:
  - 'npm i -g firebase-tools'
install: ./predeploy.sh
after_install: true
before_script: true
script: true
after_script: true
deploy:
  provider: firebase
  token:
    secure: "awkUtRwOmzWeNXGDRcrWdz/FKKRgLLnU2VXI/xag0lfQkCv7HsxUfv5YfLE+UzCViVvTafZzy+VE0q2MHMIM+TvGpNDply8seW61vTXJVLyguZopVlNgiePkg26+ZzLNQvCPbENAlxgS9c90VH5lIPC1Ya+VyJ7IDLBWt+Rhu6d6CGBImcbwxiwuWyGmHpvm3hsLcsNRDehsYtiCLvKzEWdu5GRsGKfrwCG4AJjIAXaMl/EZrSyZ9tPbpsVDMbZVB0+YIgee0uRfwasLn6+IoxB4PNhuEhYlSMRghRcH9S/UNq9mVVD9vhs+U58yPBca5f+gkyjNoMc6Om1D73A6ZRyzhL8HtFrnOuazaji9oAREv+7GvvcOIfMcA0bkFuldzXNc9d+dqQI3qhdeT1CRkT0OZyDrJnQ2XT9LrqKknfdwRaE4XGcPxcuQ2jsLTKCH7maom8ZzlM2a362qfMuQJa4aeDbiCbBtTH1cXo+SFlWQ4NzZr0FOWs6eHPqRo2RIjJw4mDfR0S/a913gu3kizlBfczKQ7L4rTcsiWZgMf57oTaUMCmjr1OyvHo1SKIDkmn+tRWUjPGP9CsS7eVC/ksbjPHfUTqVGayZQK5osDSPKor3XLIk46cqwd9MW9XMUygYadQbOzNeR8IstDWOY8U7nMS4NpYBayj1CaWVwxjo="
  project: "scheduler-front"
  on:
    branch: firebase